services:
  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    image: postgres:${COMPOSE_PROJECT_NAME}
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGSSLMODE: disable
    command: ["postgres", "-c", "ssl=off"] # supply a certificate to enable

  redis:
    build:
      context: ./.docker/redis
      dockerfile: Dockerfile
    image: redis:${COMPOSE_PROJECT_NAME}
    container_name: cache
    expose:
      - 6379

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME}_postgres_data
