version: "3.9"
services:
  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    image: postgres:changemename
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGSSLMODE: disable
    command: ["postgres", "-c", "ssl=off"] # supply a certificate to enable

  redis:
    build:
      context: ./.docker/redis
      dockerfile: Dockerfile
    image: redis:changemename
    container_name: cache
    expose:
      - 6379
