version: "3.8"
services:
  backend:
    build:
      context: ./packages/medusa
      dockerfile: Dockerfile
    container_name: medusa
    env_file: .env
    volumes:
      - ./packages/medusa:/app
      - /app/node_modules
    environment:
      STORE_CORS: ${STORE_CORS}
      ADMIN_CORS: ${ADMIN_CORS}
      AUTH_CORS: ${AUTH_CORS}
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
    ports:
      - "9000:9000"
      - "7001:7001"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  storefront:
    build:
      context: ./site
      dockerfile: Dockerfile
    container_name: astro
    ports:
      - "4321:4321"
    volumes:
      # mount local source into container
      - ./site:/app
      # paths below are ephemeral volumes
      - /app/.tscache
      - /app/dist
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: