version: "3.8"
services:
  backend:
    build:
      context: ./packages/medusa
      dockerfile: Dockerfile
    container_name: medusa
    env_file: .env
    environment:
      STORE_CORS: ${STORE_CORS}
      ADMIN_CORS: ${ADMIN_CORS}
      AUTH_CORS: ${AUTH_CORS}
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # storefront:
  #   build:
  #     context: ./site
  #     dockerfile: Dockerfile
  #   container_name: medusa-storefront
  #   depends_on:
  #     - backend